# Generated by Django 3.0.2 on 2020-02-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_local_telefonecontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='telefonecontato',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='irmaocontato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
