# Generated by Django 3.0.2 on 2020-02-03 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20200203_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='telefonecontato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='usuario',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
