# Generated by Django 3.0.2 on 2020-02-04 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_auto_20200203_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='dataini',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Irmao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contatolocal', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(choices=[('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro')], max_length=2)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('datanasc', models.DateField(blank=True, null=True)),
                ('estadocivil', models.CharField(max_length=20)),
                ('telefonecontato', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('parentes', models.TextField(max_length=200)),
                ('fotolink', models.CharField(max_length=100)),
                ('observacoes', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('CAT', 'Comunhão Ativo'), ('CAU', 'Comunhão Ausente'), ('DIS', 'Disciplina'), ('VIS', 'Visitante'), ('PEL', 'Pediu Lugar a Mesa')], max_length=3)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Local')),
                ('usuario', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Irmaos',
            },
        ),
    ]
