# Generated by Django 3.0.2 on 2020-02-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200203_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmao',
            name='estadocivil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='irmao',
            name='fotolink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='irmao',
            name='observacoes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='irmao',
            name='parentes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
