# Generated by Django 3.0.2 on 2020-02-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200203_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmao',
            name='telefonecontato',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='telefonecontato',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
