# Generated by Django 3.0.2 on 2020-02-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200204_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='statuslocal',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='irmao',
            name='estadocivil',
            field=models.CharField(blank=True, choices=[('CAS', 'Casado'), ('SOL', 'Solteiro'), ('DIV', 'Divorciado'), ('SEP', 'Separado'), ('VIU', 'Viúvo')], max_length=20, null=True),
        ),
    ]
