# Generated by Django 3.0.2 on 2020-02-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200204_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='statuslocal',
            field=models.CharField(choices=[('A', 'Assembléia'), ('I', 'Informal')], default='A', max_length=1),
        ),
    ]
