# Generated by Django 3.0.2 on 2020-02-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200205_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='cidade',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
