# Generated by Django 3.0.2 on 2020-02-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200205_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmao',
            name='emailcontato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
    ]
